### ISSUE TITLE
Pause Menu cannot be interacted when in Multiplayer lobby

### ISSUE THREAD

**Issue by niefia** [ac-arcana/cogito-arcana#42]
**Cogito and Godot Engine Version:**
Godot Engine 4.3, Cogito is current branch version
Also tested & issue present in Godot 4.2.2

**Description:**

The Multiplayer Pause Menu works fine in single-player mode

However when joining a lobby (only tested through LAN on same pc so far) the Multiplayer Pause Menu becomes un-interactable, and appears behind the HUD UI.

Draw order issue can be fixed by Z-Index the Multiplayer Pause Menu above the HUD.  
Unsure of the cause of the un-intractability but may be due to location in the scene tree, will look into it

**Reproduction steps:**

1. Start New game
2. Open Multiplayer Pause Menu in Singleplayer with Esc key
3. Click Multiplayer->LAN->Host via LAN
4. Close (singleplayer) Pause menu which seems to appear on joining multiplayer session (_guess it's another bug but lower priority_)
5. Open the Multiplayer Pause Menu in Multiplayer with Esc key, appears un-interactable and behind HUD UI here.

**Comment by niefia** [comment]
Yeah the issues is with scene tree, can be fixed super easily by just swapping the MultiplayerLevelSpawner and MultiplayerPlayerSpawner around in the scene tree
![image](https://github.com/user-attachments/assets/360a8277-cc3c-4a4b-9b71-b2fa4ad83c49)

**Comment by ac-arcana** [comment]
Thanks for the fix! Merged, so I'll close the issue.
