### ISSUE TITLE
Interaction Prompt UI being synced between different players

### ISSUE THREAD

**Issue by niefia** [ac-arcana/cogito-arcana#43]
**Cogito and Godot Engine Version:**
Godot Engine 4.3, Cogito is current branch version
Also tested & issue present in Godot 4.2.2

**Description:**
Interaction Prompt UI being synced between different players

**Reproduction steps:**
1. Launch multiple instances and all join a lobby together
2. On any instance (seems to be possible for host to client and client to host) walk up to the nearest hint
3. Interaction Prompt UI may show for all players, doesn't always happen but seems to be most common with Hints & Doors, never seems to happen with any Carryables.

**Expected behavior:**
Interaction Prompt UI only displays for relevant player

**Screenshots:**
![image](https://github.com/user-attachments/assets/a37bff00-75e9-4593-adb6-819f8583a646)

**Comment by niefia** [comment]
Adding to this it seems to always be the same interactables that are having this isssue, not random.
However I can't see anything unique about the setup of _those_  interactables that's causing this issue.

For example with these hints:
![image](https://github.com/user-attachments/assets/3b08a7cf-daf5-4539-8045-9faa47ef40a7)
The left hint is always fine, and the right one always has this issue.

Changing the text of the readable had no effect, but somehow changing the position of the right hint to 1,1,1 makes it  work fine. 

Another thing is that the interaction prompt always works as well, so player A can trigger an interaction in front of player B when this happens. Even possible when player A has a totally different prompt in front of them.

**Comment by ac-arcana** [comment]
My guess on this would be that since the client players are full players, they have an interactor ray that is also checking for inputs every frame.

**Comment by ac-arcana** [comment]
See if 39bec90f74dc3b8ee72f7e77583409489683dfe3 fixes this issue. I am simply calling queue_free on client PlayerInteractionComponent.
